"use strict";
const CONFIG={officeName:"Joseph LaValley, DDS",officeEmail:"OFFICE_EMAIL_GOES_HERE",storageKey:"lavelley-dental-demo-profile-v2"};
const conditions=["Heart disease","High blood pressure","Diabetes","Bleeding disorder","Stroke","Asthma/COPD","Sleep apnea","Kidney disease","Liver disease","Thyroid disease","Seizures","Cancer","HIV/AIDS","Arthritis","Osteoporosis","Joint replacement","Artificial heart valve","Pacemaker","Depression/anxiety","Substance-use disorder","None known"];
const symptoms=["Tooth pain","Sensitivity","Broken tooth/filling","Swelling","Bleeding gums","Jaw pain/clicking","Dry mouth","Mouth sore","Bad breath","Grinding/clenching","Sleep concerns","Cosmetic concern","None"];
const $=s=>document.querySelector(s),form=$("#intakeForm"),steps=[...document.querySelectorAll(".step")];let step=0,packetHtml="";
const esc=v=>String(v??"").replace(/[&<>\"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
function show(id){document.querySelectorAll(".screen").forEach(x=>x.classList.toggle("active",x.id===id));scrollTo({top:0,behavior:"smooth"})}
function toast(msg){const x=$("#toast");x.textContent=msg;x.classList.add("show");setTimeout(()=>x.classList.remove("show"),2400)}
function fillChoices(id,items,name){const box=$(id);items.forEach(item=>{const l=document.createElement("label");l.innerHTML=`<input type="checkbox" name="${name}" value="${item}"><span>${item}</span>`;box.append(l)})}
fillChoices("#conditions",conditions,"conditions");fillChoices("#symptoms",symptoms,"symptoms");
const today=new Date(),oldest=new Date(today.getFullYear()-120,today.getMonth(),today.getDate());
$("#dob").max=today.toISOString().slice(0,10);$("#dob").min=oldest.toISOString().slice(0,10);$("#signatureDate").value=today.toISOString().slice(0,10);$("#signatureDate").max=today.toISOString().slice(0,10);
function renderStep(){steps.forEach((x,i)=>x.classList.toggle("active",i===step));$("#stepLabel").textContent=`Question ${step+1} of ${steps.length}`;$("#stepTitle").textContent=steps[step].dataset.title;$("#progressBar").style.width=`${((step+1)/steps.length)*100}%`;$("#backBtn").style.visibility=step?"visible":"hidden";$("#nextBtn").style.display=step===steps.length-1?"none":"block";$("#generateBtn").style.display=step===steps.length-1?"block":"none";$("#error").textContent="";steps[step].querySelector("input,select,textarea")?.focus({preventScroll:true})}
function validateStep(){const fields=[...steps[step].querySelectorAll("[required]")];for(const field of fields){if(!field.checkValidity()){field.reportValidity();$("#error").textContent="Required — please answer before continuing.";field.focus();return false}}return true}
$("#nextBtn").onclick=()=>{if(validateStep()){step++;renderStep();scrollTo({top:70,behavior:"smooth"})}};$("#backBtn").onclick=()=>{if(step){step--;renderStep();scrollTo({top:70,behavior:"smooth"})}};
function serialize(){const data={};for(const [k,v] of new FormData(form))data[k]=data[k]?[].concat(data[k],v):v;return data}
function restore(data){form.reset();Object.entries(data).forEach(([k,v])=>{const controls=form.elements.namedItem(k);if(!controls)return;const vals=[].concat(v);if(controls instanceof RadioNodeList||controls.length&&!controls.tagName)[...controls].forEach(c=>{if(c.type==="checkbox"||c.type==="radio")c.checked=vals.includes(c.value)});else controls.value=v});$("#signatureDate").value=today.toISOString().slice(0,10);updateSignature();toggleInsurance()}
function reusableData(){const d=serialize();delete d.signatureName;delete d.signatureDate;delete d.accuracyConsent;delete d.careConsent;return d}
$("#saveBtn").onclick=()=>{localStorage.setItem(CONFIG.storageKey,JSON.stringify(reusableData()));toast("Profile saved only on this device")};
$("#newBtn").onclick=()=>{form.reset();$("#signatureDate").value=today.toISOString().slice(0,10);step=0;renderStep();show("wizard")};
$("#savedBtn").onclick=()=>{const raw=localStorage.getItem(CONFIG.storageKey);if(!raw)return toast("No saved patient profile found on this device");restore(JSON.parse(raw));step=0;renderStep();show("wizard");toast("Saved profile loaded — please review every answer")};
$("#homeBtn").onclick=()=>{if($("#wizard").classList.contains("active")&&!confirm("Return home? Your unsaved answers will remain only until this page closes."))return;show("home")};
function titleCase(value){return value.toLowerCase().replace(/(^|[\s.'-])([a-z])/g,(m,a,b)=>a+b.toUpperCase())}
document.querySelectorAll("[data-capitalize]").forEach(x=>x.addEventListener("blur",()=>x.value=titleCase(x.value.trim())));document.querySelectorAll("[data-upper]").forEach(x=>x.addEventListener("input",()=>x.value=x.value.toUpperCase()));
function updateSignature(){$("#signaturePreview").textContent=$("#signatureName").value.trim()||"Your Signature"}$("#signatureName").addEventListener("input",updateSignature);
function toggleInsurance(){const yes=$("#insured").value==="Yes";$("#insuranceFields").hidden=!yes;$("#insuranceFields").querySelectorAll("input").forEach(x=>x.required=yes)}$("#insured").addEventListener("change",toggleInsurance);
const labelMap={firstName:"First name",lastName:"Last name",dob:"Date of birth",pronouns:"Pronouns",phone:"Phone",email:"Patient email",address:"Address",city:"City",state:"State",zip:"ZIP",emergencyName:"Emergency contact",emergencyRelation:"Relationship",emergencyPhone:"Emergency phone",insured:"Using insurance",insurer:"Insurance company",memberId:"Member ID",groupNumber:"Group number",subscriber:"Subscriber",conditions:"Medical conditions",otherConditions:"Other conditions",allergies:"Allergies",medications:"Medications",physician:"Primary physician",physicianPhone:"Physician phone",surgeries:"Surgeries/hospitalizations",pregnant:"Pregnancy",tobacco:"Tobacco/nicotine",premed:"Antibiotic premedication",lastDentalVisit:"Last dental visit",dentalAnxiety:"Dental anxiety",dentalConcerns:"Current concerns",symptoms:"Symptoms",symptomDetails:"Symptom details",signatureName:"Signed by",signatureDate:"Date signed"};
function section(title,keys,data){const rows=keys.filter(k=>data[k]).map(k=>`<p><strong>${esc(labelMap[k]||k)}:</strong> ${esc([].concat(data[k]).join(", "))}</p>`).join("");return rows?`<h2>${title}</h2><div class="packet-grid">${rows}</div>`:""}
function buildPacket(data){return `<header><p>DIGITAL PATIENT INTAKE</p><h1>${esc(CONFIG.officeName)}</h1><p><strong>Office delivery:</strong> ${esc(CONFIG.officeEmail)}</p></header>${section("Patient",["firstName","lastName","dob","pronouns","phone","email","address","city","state","zip"],data)}${section("Emergency & Insurance",["emergencyName","emergencyRelation","emergencyPhone","insured","insurer","memberId","groupNumber","subscriber"],data)}${section("Medical History",["conditions","otherConditions","allergies","medications","physician","physicianPhone","surgeries","pregnant","tobacco","premed"],data)}${section("Dental History",["lastDentalVisit","dentalAnxiety","dentalConcerns","symptoms","symptomDetails"],data)}<h2>Attestation</h2><p>I confirm the information is accurate to the best of my knowledge.</p><p class="packet-signature">${esc(data.signatureName)}</p><p>Signed ${esc(data.signatureDate)}</p><footer><p><strong>Prototype:</strong> Generated locally on the patient’s device. Secure production delivery is not enabled.</p></footer>`}
form.addEventListener("submit",e=>{e.preventDefault();if(!validateStep())return;const data=serialize();packetHtml=buildPacket(data);$("#packetBody").innerHTML=packetHtml;if($("#saveProfileCheck").checked)localStorage.setItem(CONFIG.storageKey,JSON.stringify(reusableData()));show("thanks")});
$("#viewPacketBtn").onclick=()=>show("packet");$("#packetBack").onclick=()=>show("thanks");$("#printBtn").onclick=()=>window.print();$("#deleteBtn").onclick=()=>{form.reset();packetHtml="";$("#packetBody").replaceChildren();show("home");toast("Session data deleted")};
renderStep();
