"use strict";
const CONFIG={officeName:"Joseph LaValley, DDS",officeEmail:"OFFICE_EMAIL_GOES_HERE",storageKey:"lavelley-dental-demo-profile-v2"};
const conditions=["Heart disease","High blood pressure","Diabetes","Bleeding disorder","Stroke","Asthma/COPD","Sleep apnea","Kidney disease","Liver disease","Thyroid disease","Seizures","Cancer","HIV/AIDS","Arthritis","Osteoporosis","Joint replacement","Artificial heart valve","Pacemaker","Depression/anxiety","Substance-use disorder","None known"];
const symptoms=["Tooth pain","Sensitivity","Broken tooth/filling","Swelling","Bleeding gums","Jaw pain/clicking","Dry mouth","Mouth sore","Bad breath","Grinding/clenching","Sleep concerns","Cosmetic concern","None"];
const $=s=>document.querySelector(s),form=$("#intakeForm"),steps=[...document.querySelectorAll(".step")];let step=0,packetHtml="",medicationList=[],insuranceImages={front:"",back:""},medicationTimer;
const esc=v=>String(v??"").replace(/[&<>\"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
function show(id){document.querySelectorAll(".screen").forEach(x=>x.classList.toggle("active",x.id===id));scrollTo({top:0,behavior:"smooth"})}
function toast(msg){const x=$("#toast");x.textContent=msg;x.classList.add("show");setTimeout(()=>x.classList.remove("show"),2400)}
function fillChoices(id,items,name){const box=$(id);items.forEach(item=>{const l=document.createElement("label");l.innerHTML=`<input type="checkbox" name="${name}" value="${item}"><span>${item}</span>`;box.append(l)})}
fillChoices("#conditions",conditions,"conditions");fillChoices("#symptoms",symptoms,"symptoms");
const today=new Date();
const monthNames=["January","February","March","April","May","June","July","August","September","October","November","December"];
monthNames.forEach((name,index)=>$("#birthMonth").add(new Option(name,String(index+1))));
for(let year=today.getFullYear();year>=today.getFullYear()-120;year--)$("#birthYear").add(new Option(String(year),String(year)));
function fillBirthDays(){const month=Number($("#birthMonth").value),year=Number($("#birthYear").value)||2000,previous=$("#birthDay").value,total=month?new Date(year,month,0).getDate():31;$("#birthDay").replaceChildren(new Option("Day",""));for(let day=1;day<=total;day++)$("#birthDay").add(new Option(String(day),String(day)));if(Number(previous)<=total)$("#birthDay").value=previous}
$("#birthMonth").addEventListener("change",fillBirthDays);$("#birthYear").addEventListener("change",fillBirthDays);fillBirthDays();
$("#signatureDate").value=today.toISOString().slice(0,10);$("#signatureDate").max=today.toISOString().slice(0,10);form.elements.lastDentalVisit.max=today.toISOString().slice(0,10);
function renderStep(){steps.forEach((x,i)=>x.classList.toggle("active",i===step));$("#stepLabel").textContent=`Question ${step+1} of ${steps.length}`;$("#stepTitle").textContent=steps[step].dataset.title;$("#progressBar").style.width=`${((step+1)/steps.length)*100}%`;$("#backBtn").style.visibility=step?"visible":"hidden";$("#nextBtn").style.display=step===steps.length-1?"none":"block";$("#generateBtn").style.display=step===steps.length-1?"block":"none";$("#error").textContent="";steps[step].querySelector("input,select,textarea")?.focus({preventScroll:true})}
function validateStep(){const fields=[...steps[step].querySelectorAll("[required]")];for(const field of fields){if(!field.checkValidity()){field.reportValidity();$("#error").textContent="Required — please answer before continuing.";field.focus();return false}}return true}
$("#nextBtn").onclick=()=>{if(validateStep()){step++;renderStep();scrollTo({top:70,behavior:"smooth"})}};$("#backBtn").onclick=()=>{if(step){step--;renderStep();scrollTo({top:70,behavior:"smooth"})}};
function serialize(){const data={};for(const [k,v] of new FormData(form))data[k]=data[k]?[].concat(data[k],v):v;if(data.birthYear&&data.birthMonth&&data.birthDay)data.dob=`${data.birthYear}-${String(data.birthMonth).padStart(2,"0")}-${String(data.birthDay).padStart(2,"0")}`;return data}
function restore(data){form.reset();Object.entries(data).forEach(([k,v])=>{const controls=form.elements.namedItem(k);if(!controls)return;const vals=[].concat(v);if(controls instanceof RadioNodeList||controls.length&&!controls.tagName)[...controls].forEach(c=>{if(c.type==="checkbox"||c.type==="radio")c.checked=vals.includes(c.value)});else controls.value=v});medicationList=data.medications&&data.medications!=="None"?String(data.medications).split("\n"):(data.medications?["None"]:[]);renderMedications();$("#signatureDate").value=today.toISOString().slice(0,10);updateSignature();toggleInsurance()}
function reusableData(){const d=serialize();delete d.signatureName;delete d.signatureDate;delete d.accuracyConsent;delete d.careConsent;return d}
$("#saveBtn").onclick=()=>{localStorage.setItem(CONFIG.storageKey,JSON.stringify(reusableData()));toast("Profile saved only on this device")};
function resetExtras(){medicationList=[];insuranceImages={front:"",back:""};$("#medications").value="";["#frontPreview","#backPreview"].forEach(id=>{const image=$(id);image.removeAttribute("src");image.classList.remove("ready")});$("#insuranceStatus").textContent="Card images are optional. Coverage verification occurs through the office’s insurance system."}
$("#newBtn").onclick=()=>{form.reset();resetExtras();$("#signatureDate").value=today.toISOString().slice(0,10);step=0;renderStep();show("wizard")};
$("#savedBtn").onclick=()=>{const raw=localStorage.getItem(CONFIG.storageKey);if(!raw)return toast("No saved patient profile found on this device");restore(JSON.parse(raw));step=0;renderStep();show("wizard");toast("Saved profile loaded — please review every answer")};
function returnHome(){if($("#wizard").classList.contains("active")&&!confirm("Return to the home screen? Your current answers will stay here unless you start a new patient form."))return;show("home")}
$("#homeBtn").onclick=returnHome;$("#wizardHomeBtn").onclick=returnHome;
function titleCase(value){return value.toLowerCase().replace(/(^|[\s.'-])([a-z])/g,(m,a,b)=>a+b.toUpperCase())}
document.querySelectorAll("[data-capitalize]").forEach(x=>x.addEventListener("blur",()=>x.value=titleCase(x.value.trim())));document.querySelectorAll("[data-upper]").forEach(x=>x.addEventListener("input",()=>x.value=x.value.toUpperCase()));
function updateSignature(){$("#signaturePreview").textContent=$("#signatureName").value.trim()||"Your Signature"}$("#signatureName").addEventListener("input",updateSignature);
function toggleInsurance(){const yes=$("#insured").value==="Yes";$("#insuranceFields").hidden=!yes;$("#insuranceFields").querySelectorAll('input:not([type="file"]):not([type="hidden"])').forEach(x=>x.required=yes)}$("#insured").addEventListener("change",toggleInsurance);
$("#addressSearchBtn").addEventListener("click",async()=>{const query=$("#addressSearch").value.trim();if(query.length<8){$("#addressStatus").textContent="Enter a fuller street address, city, and state first.";return}$("#addressStatus").textContent="Searching addresses…";try{const url=`https://geocoding.geo.census.gov/geocoder/locations/onelineaddress?address=${encodeURIComponent(query)}&benchmark=Public_AR_Current&format=json`;const data=await fetch(url).then(r=>{if(!r.ok)throw Error();return r.json()});const match=data?.result?.addressMatches?.[0];if(!match){$("#addressStatus").textContent="No close match found. Check the spelling or enter the address manually below.";return}const c=match.addressComponents||{};form.elements.address.value=[c.fromAddress,c.preDirection,c.preType,c.streetName,c.suffixType,c.suffixDirection].filter(Boolean).join(" ");form.elements.city.value=titleCase(c.city||"");form.elements.state.value=c.state||"";form.elements.zip.value=c.zip||"";$("#addressStatus").textContent=`Matched: ${match.matchedAddress}. Please confirm the fields below.`}catch{$("#addressStatus").textContent="Address search is temporarily unavailable. Enter the address manually below."}});
function captureCard(input,preview,side){input.addEventListener("change",()=>{const file=input.files?.[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{insuranceImages[side]=reader.result;preview.src=reader.result;preview.classList.add("ready");const captured=[insuranceImages.front&&"front",insuranceImages.back&&"back"].filter(Boolean);$("#insuranceCardStatus").value=captured.length===2?"Front and back card images captured":`${captured[0]||"One"} card image captured`;$("#insuranceStatus").textContent=$("#insuranceCardStatus").value};reader.readAsDataURL(file)})}
captureCard($("#insuranceFront"),$("#frontPreview"),"front");captureCard($("#insuranceBack"),$("#backPreview"),"back");
function renderMedications(){$("#medications").value=medicationList.join("\n");$("#medications").dispatchEvent(new Event("input"))}
function addMedication(name){if(!name||medicationList.includes(name))return;medicationList.push(name);renderMedications();$("#medSearch").value="";$("#medResults").replaceChildren()}
$("#medNoneBtn").onclick=()=>{medicationList=["None"];renderMedications();$("#medResults").replaceChildren()};$("#clearMedsBtn").onclick=()=>{medicationList=[];renderMedications()};
$("#medSearch").addEventListener("input",()=>{clearTimeout(medicationTimer);const term=$("#medSearch").value.trim();$("#medResults").replaceChildren();if(term.length<3)return;medicationTimer=setTimeout(async()=>{const results=$("#medResults");results.textContent="Searching medications…";try{const url=`https://rxnav.nlm.nih.gov/REST/approximateTerm.json?term=${encodeURIComponent(term)}&maxEntries=8&option=1`;const data=await fetch(url).then(r=>{if(!r.ok)throw Error();return r.json()});const names=[...new Set((data?.approximateGroup?.candidate||[]).map(x=>x.name).filter(Boolean))];results.replaceChildren();names.forEach(name=>{const b=document.createElement("button");b.type="button";b.textContent=name;b.onclick=()=>addMedication(name);results.append(b)});if(!names.length)results.textContent="No RxNorm match found. Check the spelling or ask the dental team for help."}catch{results.textContent="Medication search is temporarily unavailable. Try again or ask the dental team for help."}},350)});
const labelMap={firstName:"First name",lastName:"Last name",dob:"Date of birth",pronouns:"Pronouns",phone:"Phone",email:"Patient email",address:"Address",city:"City",state:"State",zip:"ZIP",emergencyName:"Emergency contact",emergencyRelation:"Relationship",emergencyPhone:"Emergency phone",insured:"Using insurance",insurer:"Insurance company",memberId:"Member ID",groupNumber:"Group number",subscriber:"Subscriber",insuranceCardStatus:"Insurance card",conditions:"Medical conditions",otherConditions:"Other conditions",allergies:"Allergies",medications:"Medications",physician:"Primary physician",physicianPhone:"Physician phone",surgeries:"Surgeries/hospitalizations",pregnant:"Pregnancy",tobacco:"Tobacco/nicotine",premed:"Antibiotic premedication",lastDentalVisit:"Last dental visit",dentalAnxiety:"Dental anxiety",dentalConcerns:"Current concerns",symptoms:"Symptoms",symptomDetails:"Symptom details",signatureName:"Signed by",signatureDate:"Date signed"};
function section(title,keys,data){const rows=keys.filter(k=>data[k]).map(k=>`<p><strong>${esc(labelMap[k]||k)}:</strong> ${esc([].concat(data[k]).join(", "))}</p>`).join("");return rows?`<h2>${title}</h2><div class="packet-grid">${rows}</div>`:""}
function buildPacket(data){const cardImages=insuranceImages.front||insuranceImages.back?`<h2>Insurance Card Images</h2><div class="packet-grid">${insuranceImages.front?`<p><strong>Front</strong><br><img src="${insuranceImages.front}" alt="Insurance card front" style="max-width:100%;max-height:240px"></p>`:""}${insuranceImages.back?`<p><strong>Back</strong><br><img src="${insuranceImages.back}" alt="Insurance card back" style="max-width:100%;max-height:240px"></p>`:""}</div>`:"";return `<header><p>DIGITAL PATIENT INTAKE</p><h1>${esc(CONFIG.officeName)}</h1><p><strong>Office delivery:</strong> ${esc(CONFIG.officeEmail)}</p></header>${section("Patient",["firstName","lastName","dob","pronouns","phone","email","address","city","state","zip"],data)}${section("Emergency & Insurance",["emergencyName","emergencyRelation","emergencyPhone","insured","insurer","memberId","groupNumber","subscriber","insuranceCardStatus"],data)}${cardImages}${section("Medical History",["conditions","otherConditions","allergies","medications","physician","physicianPhone","surgeries","pregnant","tobacco","premed"],data)}${section("Dental History",["lastDentalVisit","dentalAnxiety","dentalConcerns","symptoms","symptomDetails"],data)}<h2>Attestation</h2><p>I confirm the information is accurate to the best of my knowledge.</p><p class="packet-signature">${esc(data.signatureName)}</p><p>Signed ${esc(data.signatureDate)}</p><footer><p>This product uses publicly available RxNorm data from the U.S. National Library of Medicine; NLM does not endorse this product.</p><p><strong>Prototype:</strong> Generated locally on the patient’s device.</p></footer>`}
form.addEventListener("submit",e=>{e.preventDefault();if(!validateStep())return;const data=serialize();packetHtml=buildPacket(data);$("#packetBody").innerHTML=packetHtml;if($("#saveProfileCheck").checked)localStorage.setItem(CONFIG.storageKey,JSON.stringify(reusableData()));show("thanks")});
$("#viewPacketBtn").onclick=()=>show("packet");$("#packetBack").onclick=()=>show("thanks");$("#printBtn").onclick=()=>window.print();$("#deleteBtn").onclick=()=>{form.reset();resetExtras();packetHtml="";$("#packetBody").replaceChildren();show("home");toast("Session data deleted")};
renderStep();
